config/routes.rb
Map::Application.routes.draw do
  devise_for :users

	root :to => "locations#index"

  resources :locations

end

app/models/location.rb
class Location < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :lat
	validates_presence_of :long
	
	before_create :set_pending
	
	def set_pending
		self.status = "Pending" if self.status.nil?
	end
	
	def self.search(search)
		if search
			find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model , :remember_me
  attr_accessible :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.xml
  before_filter :getlocation, :only => [:edit, :update, :destroy]
  
  def index
    @locations = Location.search(params[:search])
    
    respond_to do |format|
      format.html
      format.xml  { render :xml => @locations }
    end
  end

  # GET /locations/new
  # GET /locations/new.xml
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/1/edit
  def edit
    
  end

  # POST /locations
  # POST /locations.xml
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to(locations_path, :notice => 'Location was successfully created.') }
        format.xml  { render :xml => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.xml
  def update
    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to(locations_path, :notice => 'Location was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.xml
  def destroy
    @location.destroy

    respond_to do |format|
      format.html { redirect_to(locations_url) }
      format.xml  { head :ok }
    end
  end
  private
  def getlocation
  	@location = Location.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Map</title>
  <%= stylesheet_link_tag :all %>
  <style>
  	body
  	{
  		font-family: sans-serif;
  		font-size: small;
  		background: #BFE3FE;
  		color: #BFE3FE;
  	}
  	a, a:visited
  	{
  		text-decoration: none;
  		color: #BFE3FE;
  	}
  	a:hover
  	{
  		background: none;
  		text-decoration: underline;
  		color: #BFE3FE;
  	}
  	h1
  	{
  		font-size: medium;
  	}
  	#header
  	{
  		height: 1em;
  		background: #3B5998; 
  		color: white;
  		padding: 1em;
  		margin-bottom: 0.5em;
  	}
  	#site_name
  	{
  		float: left;
  		font-size: medium;
  		font-weight: bold;
  	}
  	#user_nav
  	{
  		float: right;
  	}
  	#wrapper
  	{
  		position: absolute;
  		width: 80em;
  		left: 50%;
  		margin-left: -41em;
  		background: white;
  		padding: 1em;
  		color: #0033CC;
  	}
  	#main
  	{
  		background: #00248E;
  		color: white;
  		padding: 1em;
  		height: 31em;
  	}
  	#left_col
  	{
  		background: #3B5998; 
  		float: left;
  		width: 25em;
  		height: 29em;
  		padding: 1em;
  		margin-right: 1em;
  	}
  	#right_col
  	{
  		background: #3B5998; 
  		float: left;
  		width: 50em;
  	}
  	#place
  	{
  		position: absolute;
  		left: 56em;
  		top: 18em;
  		color: red;
  		z-index: 1;
  	}
  	#map_search, #map_canvas
  	{
  		width: 50em;
  		height: 30em;
  		background: #3B5998; 
  	}
  	#list
  	{
  		height: 20em;
  		overflow: auto;
  	}
  	#notice
  	{
  		height: 1em;
  	}
  	#loc_name
  	{
  		width:24em;
  	}
  	#loc_link
  	{
  		font-style: italic;
  		font-size: 0.8em;
  	}
  </style>
  <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAzr2EBOXUKnm_jVnk0OJI7xSosDVG8KKPE1-m51RBrvYughuyMxQ-i1QfUnH94QxWIa6N4U6MouMmBA" type="text/javascript"></script>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body onload="initialize()" onunload="GUnload()">
<div id="wrapper">
	<div id="header">
		<div id="site_name">facemap</div>
		<div id="user_nav">
			<% if user_signed_in? %>
				Signed in as <%= current_user.email %>. Not you? <%= link_to 'Sign Out', destroy_user_session_path %>
			<% else %>
				<%= link_to 'Sign In', new_user_session_path %> or <%= link_to 'Sign Up', new_user_registration_path %>
			<% end %>
		</div>
	</div>
	<div id="main">
		<%= yield %>
	</div>
</div>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat, :onclick => "location_edit()"%>
  </div>
  <div class="field">
    <%= f.label :long %><br />
    <%= f.text_field :long, :onclick => "location_edit()"%>
  </div>
  <% if user_signed_in? %>
	  <div class="field">
		<%= f.hidden_field :status, :value => "Approved"%>
	  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<div id="left_col">
  <h1>Edit location</h1>
  <%= render 'form' %>
</div>
<div id="right_col">
  <div id="map_search"></div>
</div>
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div id="left_col">
	<p id="notice"><%= notice %></p>

	<% form_tag locations_path, :method => 'get' do %>
		<p>
			<%= text_field_tag :search, params[:search] %>
			<%= submit_tag "Search", :name => nil %>
		</p>
	<% end %>

	<h1>List of Locations</h1>
	<div id="list">
		<% @locations.each do |location| %>
			<% if user_signed_in? %>

				<div id="loc_name">*<%= location.name %></div>
				<div id="loc_link"><%= location.status %> || <%= link_to 'Edit', edit_location_path(location) %> |
				<%= link_to 'Delete', location, :confirm => 'Are you sure?', :method => :delete %> | <a href="#" onClick="location_search('<%= location.name %>', '<%= location.lat %>', '<%= location.long %>')">Show on map</a></div>
			<% elsif location.status.eql?("Approved")%>
				<div id="loc_name">*<%= location.name %></div>
				<div id="loc_link"><a href="#" onClick="location_search('<%= location.name %>', '<%= location.lat %>', '<%= location.long %>')">Show on map</a></div>
			<% end %>
		<% end %>
	</div>
</div>
<div id="right_col">
	<div id="place"></div>
	<div id="map_search">Click <u>Show on map</u></div>
</div>
<% if user_signed_in? %>
<%= link_to 'Add Location', new_location_path %>
<% else %>
<%= link_to 'Suggest Location', new_location_path %>
<% end %>

app/views/locations/new.html.erb
<div id="left_col">
  <h1>New location</h1>
  <%= render 'form' %>
</div>
<div id="right_col">
  <div id="map_canvas"></div>
</div>
<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Lat:</b>
  <%= @location.lat %>
</p>

<p>
  <b>Long:</b>
  <%= @location.long %>
</p>

<p>
  <b>Status:</b>
  <%= @location.status %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>